name: build java

on: 
  push:
    branches: ["master"]
  pull_request: 
    branches: ["master"]
    
  workflow_dispatch:
  
jobs:
  build_java:
    runs-on: ubuntu-latest
    
    steps:
      - name: dir
        run: ls -la
        
      - uses: actions/checkout@v3
      
      - name: start
        run: |
          javac Main.java
          java Main
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: java_app
          path: Main.class
          retention-days: 5
