name: build java

on: 
  push:
    branches: ["master"]
  pull_request: 
    branches: ["master"]
    
  workflow_dispatch:
  
jobs:
  build_java:
    runs-on: ubuntu-latest
    
    steps:
      - name: dir
        run: ls -la
        
      - uses: actions/checkout@v3
      
      - name: start
        run: |
          javac Main.java
          java Main
