name: build java

on: 
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]
    
  workflow_dispatch:
  
jobs:
  build_java:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Start main file
        run: echo hello, world
