name: build java

on: 
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]
    
  workflow_dispatch:
  
jobs:
  build_java:
    runs-on: ubuntu-latest
    
    steps:
      - name: dir
        run: ls -la
        
      - uses: actions/checkout@v3
      
      - name: env report
        run: |
          ls -la
          printenv
