name: build java

on: 
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Start main file
        run:
          echo hello, world
